app = "ia_risk_manager_service"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8001"

[[services]]
  internal_port = 8001
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
